name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - '1.16.x'
          - '1.17.x'
          - '1.18.x'
        platform: [ubuntu-latest]

    name: test
    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: install golanci-linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.1

      - name: run unit tests
        run: make test

      - name: run linter
        run: make lint

      - name: upload code coverage
        uses: codecov/codecov-action@v3.1.0
        if: contains(github.ref, 'master')
        with:
          file: ./cover.out
